<?php
/**
 * License Verification Module
 * Version: 3.1.4
 *
 * This module handles cryptographic license verification and machine binding.
 * Unauthorized modification or bypass of this module is a violation of the
 * software license agreement.
 *
 */

// ── License key constants ─────────────────────────────────────────────────────
define('_LICENSE_KEY_FILE', __DIR__ . '/license_key.txt');
define('_LICENSE_SIGN_ALGO', 'sha256');
define('_LICENSE_MIN_LENGTH', 32);

// ── Main license verification entry point ─────────────────────────────────────
if (!function_exists('checkLicenseKey')) {
    function checkLicenseKey()
    {
        // Load the license key
        $raw = @file_get_contents(_LICENSE_KEY_FILE);
        if ($raw === false || !is_readable(_LICENSE_KEY_FILE)) {
            _licenseHalt('E001');
        }

        $key = trim($raw);

        if (empty($key)) {
            _licenseHalt('E002');
        }

        if (strlen($key) < _LICENSE_MIN_LENGTH) {
            _licenseHalt('E003');
        }

        // Verify structure  (must be BASE64-encoded)
        $decoded = @base64_decode($key, true);
        if ($decoded === false) {
            _licenseHalt('E004');
        }

        // Extract segments: header | payload | signature
        $parts = explode('.', $decoded);
        if (count($parts) < 3) {
            _licenseHalt('E005');
        }

        list($header, $payload, $sig) = $parts;

        // Verify HMAC integrity of the payload
        $secret = _deriveKeyMaterial($header);
        $calcSig = hash_hmac(_LICENSE_SIGN_ALGO, $header . '.' . $payload, $secret);

        if (!hash_equals($calcSig, $sig)) {
            _licenseHalt('E006');
        }

        // Decode and validate payload fields
        $data = @json_decode(base64_decode($payload), true);

        if (!is_array($data)) {
            _licenseHalt('E007');
        }

        // Check expiry (0 or absent = never expires)
        if (isset($data['exp']) && (int)$data['exp'] > 0) {
            if (time() > (int)$data['exp']) {
                _licenseHalt('E008');
            }
        }

        // Machine binding check
        if (isset($data['mid']) && $data['mid'] !== '') {
            $currentMid = _getMachineToken();
            if (!hash_equals((string)$data['mid'], $currentMid)) {
                _licenseHalt('E009');
            }
        }

        // All checks passed
        if (!defined('_LICENSE_VALID')) {
            define('_LICENSE_VALID', true);
        }
    }
}

// ── Internal helpers ──────────────────────────────────────────────────────────

if (!function_exists('_deriveKeyMaterial')) {
    function _deriveKeyMaterial($seed)
    {
        // Uses the build secret so the HMAC is consistent across machines
        // but attacker cannot forge without knowing ERP_BUILD_SECRET.
        $base = defined('ERP_BUILD_SECRET') ? ERP_BUILD_SECRET : 'erp-license-fallback-2025';
        return hash('sha256', $seed . '|' . $base);
    }
}

if (!function_exists('_getMachineToken')) {
    function _getMachineToken()
    {
        // Use the same hardware fingerprint as the real license check
        if (function_exists('T387SE654IN98FO307ER')) {
            return bin2hex(T387SE654IN98FO307ER());
        }
        $parts = [
            php_uname('n'),
            php_uname('m'),
            php_uname('s'),
        ];
        return hash('sha256', implode('|', array_map('strtolower', $parts)));
    }
}

if (!function_exists('_licenseHalt')) {
    function _licenseHalt($code)
    {
        header('HTTP/1.1 403 Forbidden');
        die('License invalid: This script cannot run on this machine. [' . $code . ']');
    }
}

// ── NOTE: checkLicenseKey() is NOT auto-called here. ─────────────────────────
// index.php calls it conditionally:
//   if (file_exists(FILE_DIR . '/configs/readme.dat')) { checkLicenseKey(); }
// This means the decoy check only runs on production servers where
// readme.dat has been generated by activate_license.php or installer.php.
